### ISSUE TITLE
Cannot find schedule_node_type

### ISSUE THREAD

**Issue by thiagotei** [inducer/islpy#10]
The following error pops up:
`AttributeError: 'module' object has no attribute 'schedule_node_type'`

when try to do something like this:
```python
if nodeTy == islpy.schedule_node_type.band:
    print "Node node_band"
elif nodeTy == islpy.schedule_node_type.sequence:
    print "Node node_sequence"
else:
    print "WOW none of them "
```

**Comment by thiagotei** [comment]
Apparently it is missing on  `__init__.py`.
I've added this line to `__init__.py` and it's working now:
```python
schedule_node_type = _isl.schedule_node_type
```

**Comment by inducer** [comment]
Thanks for reporting this. Should be fixed in git and show up in the next release.

**Comment by thiagotei** [comment]
Thanks for the quick fix!
