### ISSUE TITLE
 isl_union_access_info_from_sink missing

### ISSUE THREAD

**Issue by thisiscam** [inducer/islpy#13]
Currently UnionAccessInfo is missing the static constructors? Can this be fixed? Thanks!

**Comment by inducer** [comment]
Sure. I'd be happy to take a patch. A starting point might be to see what `gen_wrap.py` does with it.

**Comment by thisiscam** [comment]
I digged into gen_wrap. Suspecting that the issue is the following:

https://github.com/inducer/isl/blob/0ce949a1277de2e3121ed5715bdde639d6f4ba0f/include/isl/flow.h#L70

https://github.com/inducer/islpy/blob/master/gen_wrap.py#L542

Notice that in flow.h, the struct definition has a reversed "__isl_export" than the regex. This is causing a spurious warning below when I run gen_wrap:

`WARNING: func decl regexp not matched: struct __isl_export isl_union_access_info; typedef struct isl_union_access_info isl_union_access_info; struct __isl_export isl_union_flow; typedef struct isl_union_flow isl_union_flow;  __isl_constructor __isl_give isl_union_access_info *isl_union_access_info_from_sink( __isl_take isl_union_map *sink); 
`

If I understand correctly, this entire string is assumed to be a function decl when it didn't match with the struct regex, thus consuming a whole bunch of declaration following the struct decl. Not sure how you'd like to fix this though
