### ISSUE TITLE
incompatibility with nanobind 2.0

### ISSUE THREAD

**Issue by francesco-ballarin** [inducer/islpy#134]
**Describe the bug**
nanobind 2.0.0 was released two days ago (May 23, 2024). Since then, `islpy` fails to run properly, producing errors `ValueError: list.remove(x): x not in list`

**To Reproduce**
Steps to reproduce the behavior: trigger a CI run
See also https://github.com/francesco-ballarin/islpy/actions/runs/9233917330

**Expected behavior**
Compatibility with nanobind 2.0

**Environment (please complete the following information):**
Any environment tested on github actions.

**Comment by inducer** [comment]
#135 ought to address this.
