### ISSUE TITLE
Installation issues with pip3.4

### ISSUE THREAD

**Issue by aravind343** [inducer/islpy#2]
Hi,
   I had some problems while installing islpy. I tried compiling from the git source as well as installation using pip3.4. 

Header file imath.h seems to be missing and build fails when compiled from the git source. 

I tried installing with pip, I get the following errors (attached in islpy.txt)
[islpy.txt](https://github.com/inducer/islpy/files/117179/islpy.txt)

Thanks,
Aravind

**Comment by inducer** [comment]
Could you share the error messages in the build-from-git case? I think one issue is that I defaulted small-integer optimizations to on, which seems to require a reasonably recent compiler. Recent git versions default that to off, which fixed this issue for me when compiling for centos.

Simply type
```
pip install git+https://github.com/inducer/islpy.git
```
and let me know what comes back. (You reported a missing `imath.h`, which likely means you needed to `git clone --recursive`.)

**Comment by aravind343** [comment]
Thanks a lot. I checked both ways and now it works for me. I had done a git submodule init but not git clone --recursive initially.

pip with git +https worked fine as well.

Thanks,
Aravind

**Comment by intersense** [comment]
It works for me too. Thank you.

**Comment by inducer** [comment]
Relased 2016.1.1 with SIO turned off by default. Plain old `pip install islpy` should work now as well--it'd be great if you could check. Thanks for the report!
