### ISSUE TITLE
imath is slow

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/islpy#28]
[Two snippets](https://gist.github.com/kaushikcfd/1fdd939ae55c5a22d1cd4b3fbf911103) (one calling the native ISL routines, and the other islpy wrapped routines) perform equivalent ISL operations, however vastly differ in the performance:

```
kgk2@quail:~/temp$ python islpy_reproducer.py 
Time elapsed: 1.7952229976654053 secs
kgk2@quail:~/temp$ gcc -o isl_reproducer isl_reproducer.c -I$PWD/isl/build/include -L$PWD/isl/build/lib -lisl
kgk2@quail:~/temp$ ./isl_reproducer 
Time elapsed: 0.675251 seconds.
```

(both are linked against ISL-0.22.1)

**Comment by isuruf** [comment]
Difference is that islpy is using IMath whereas the isl library you have on your system is linked against GMP.
On porter if I use islpy shipped IMath,
```
Time elapsed: 1.8463377952575684 secs
```
If I make islpy link against `isl` linked with GMP, I get,
```
Time elapsed: 0.6699988842010498 secs
```

**Comment by inducer** [comment]
Thanks @isuruf, I was about to say the same thing. Linking against my system libisl:
```
$ ./a.out
Time elapsed: 0.398443 seconds
$ python zz.py
Time elapsed: 0.40033888816833496 secs
```

**Comment by inducer** [comment]
It's well-known that GMP is much faster than imath. We'd obviously want to use GMP, but that triggers a license concern, as GMP is GPL2/LGPLv3, both of which are, as I understand, no-go-zones for companies with functioning legal departments, at least for software that winds up being as tightly integrated as loopy.

That leaves us with a choice of what to do. As long as the imath option exists and works, I suppose we could just go use GMP and be unaffected (and companies could choose to go the imath route when required). In terms of concrete things to do, maybe the following would be reasonable:

- offer a build variant of isl and islpy that depends on GMP (in addition to the current imath one)
- tweak the install instructions for Loopy to explain the situation

What do you think?

**Comment by isuruf** [comment]
1. For conda, we can add GMP as it is LGPL and the conda shipped python already has readline in it which GPL.
2. For pip, we can build wheels with GMP dynamically linked. As far as I know dynamically linking doesn't trigger the GPL clauses.
3. For pip source installs imath is used.

**Comment by kaushikcfd** [comment]
Thanks, @isuruf and @inducer using ISL linked with GMP fixed the discrepancy!

**Comment by isuruf** [comment]
For conda, sympy also pulls in GMP to make integer operations faster.

**Comment by inducer** [comment]
OpenSSL's `BN_*` functions also offer bignum functionality: https://www.openssl.org/docs/manmaster/man3/ that could conceivably be tied into isl...

**Comment by inducer** [comment]
But I agree with the direction @isuruf proposes.

**Comment by kaushikcfd** [comment]
I also agree with @isuruf's proposal. Besides that, we should also scream loudly during package installation anytime `islpy` is being linked again `imath`.

**Comment by inducer** [comment]
I thought for a moment that we could make this information accessible at runtime, but if we're not using the shipped isl, we really can't tell.

**Comment by isuruf** [comment]
Something like below might work on Linux and OSX when using an external isl.

```python
try:
  ctypes.cdll.LoadLibrary(islpy._isl_cffi.__file__).isl_imath_hash
except AttributeError:
  pass
```

**Comment by inducer** [comment]
That's awful, and also brilliant. :P Thanks!

**Comment by inducer** [comment]
Found this snippet in the [isl docs](https://github.com/inducer/isl/blob/master/doc/user.pod):

```
Select the integer library to be used by C<isl>, the default is C<gmp>.
With C<imath-32>, C<isl> will use 32 bit integers, but fall back to C<imath>
for values out of the 32 bit range. In most applications, C<isl> will run
fastest with the C<imath-32> option, followed by C<gmp> and C<imath>, the
slowest.
```

#41 turns on that option by default for islpy, which might help us avoid GMP. @kaushikcfd, could you run a quick benchmark to see whether this finding holds up in your use?

If what the manual is true, then https://github.com/conda-forge/isl-feedstock should probably also drop GMP and switch to `imath-32`.

**Comment by kaushikcfd** [comment]
Indeed the islpy with imath-32 is faster. (much faster)
```
(py3env) kgk2@quail:~/temp$ python islpy_reproducer.py  # branch sio-default 
Time elapsed: 0.39672422409057617 secs
(py3env) kgk2@quail:~/temp$ ./isl_reproducer # GMP
Time elapsed: 0.676277 seconds
```

**Comment by inducer** [comment]
Oh cool. I'll merge #41 then and close this. Thanks for checking!
