### ISSUE TITLE
Mac wheel builds fail with "Error: Container action is only supported on Linux"

### ISSUE THREAD

**Issue by inducer** [inducer/islpy#36]
@isuruf, any thoughts?

https://github.com/inducer/islpy/runs/1239290649?check_suite_focus=true

**Comment by isuruf** [comment]
Will have a look. Missing wheels are in https://github.com/inducer/islpy/releases/tag/v2020.2.2 if you want to upload manually.

**Comment by inducer** [comment]
Thanks! Uploaded.
