### ISSUE TITLE
Fails to compile on macOS

### ISSUE THREAD

**Issue by thisiscam** [inducer/islpy#39]
Hi,

I just noticed that the current master fails to compile on my macOS:

```shell
isl/isl_hash.c:52:16: error: implicit declaration of function 'ffs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        table->bits = ffs(round_up(4 * (min_size + 1) / 3 - 1)) - 1;
4 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1
```

I manually added `#include <string.h>` in `isl_hash.c` and compilation works again.
I'm not sure if this is a problem is islpy (referencing the wrong submodule commit), or a bug in ISL itself?

**Comment by inducer** [comment]
#40 adds a Mac CI job. Let's see what we find.

**Comment by inducer** [comment]
Seems to work OK. Do you have a sense how your environment might be different?

**Comment by thisiscam** [comment]
Maybe it had to do with https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes#Apple-Clang-Compiler?


Similar issue: https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1034

Is the CI using the latest macOS Xcode 12 and clang?

**Comment by inducer** [comment]
Not sure what it uses, see [here](https://github.com/actions/virtual-environments).

**Comment by inducer** [comment]
Looks like this has started to show up on the CI after all: https://github.com/inducer/islpy/runs/1337452406?check_suite_focus=true

**Comment by inducer** [comment]
Let's see how #43 does.

**Comment by inducer** [comment]
Looks good on CI, closing. Let me know if this is not resolved for you.
