### ISSUE TITLE
Unable to find documentation for Access and related Dataflow objects

### ISSUE THREAD

**Issue by bollu** [inducer/islpy#4]
I wish to use the `AccessInfo` classes in `islpy`, but there's no documentation being generated for them at all as far as I can see - [link to docs here](https://documen.tician.de/islpy/ref_flow.html)

Do the bindings exist? (As in, are the bindings generated but undocumented?) Or is it that there are a todo on the islpy library? If it is the latter, then I'd be glad to help out with a couple of pointers.

Thanks!

**Comment by inducer** [comment]
Thanks for pointing this out. The code is there--I had just messed up the generation of the docs when I recently reorganized them a bit.

**Comment by bollu** [comment]
Thanks!
