### ISSUE TITLE
Unable to figure out how to construct UnionAccessInfo

### ISSUE THREAD

**Issue by bollu** [inducer/islpy#5]
Hey,

So I have a isl map, and I'd like to impose constraints on it. For example, something like this:

Given a domain like so:
```
[R, T] -> {
    S_0[i0, i1] : 0 <= i0 <= T and 0 <= i1 <= R - 1;
    S_1[i0, i1] : 0 <= i0 <= T and 0 <= i1 <= R - 1;
};
```
I'd like to assign dependencies like: 
```
[R, T] -> {
        S_0[i0, i1] -> S_0[i0 + 1, i1 - 1] : 0 <= i0 <= T - 1 and 1 <= i1 <= R - 2;
        S_0[i0, i1] -> S_0[i0 + 1, i1 + 1] : 0 <= i0 <= T - 1 and 1 <= i1 <= R - 2;
};
```

To do this, I believe that I need to use a `UnionAccessInfo` object, and assign the source and the sink correctly, right?

However, I'm not sure how to actually construct said `UnionAccessInfo`. The [isl documentation](http://isl.gforge.inria.fr/manual.pdf) seems to have a
```
isl_union_access_info_from_sink(
                __isl_take isl_union_map *sink);
```
which seems to be what I'm looking for (to create a `isl_union_access_info`). However, this is not exported by `islpy`. 

So,

1. Am I thinking of the right object for the kind of dependencies that I'd like to impose? Should I be using a different object?
2. If I'm thinking of the right object, how do I actually construct a `islpy.UnionAccessInfo`?

Thanks for the help.

**Comment by bollu** [comment]
I figured it out, you don't need `UnionAccessInfo` - just simple constraints will do!

Just for the reference of someone who stumbles upon the same problem in the future:

Just create a constraint from the input variables to the output variables.  The idea goes something like this:

### 1. Create a space 
```
{ in[x, time] -> out[x', time'] }
```

Corresponding C code:
```
    isl_space *space = isl_space_alloc(ctx, nparams, n_in_dim, n_out_dim);

    space = isl_space_set_dim_name(space, isl_dim_in, 0, "x");
    space = isl_space_set_dim_name(space, isl_dim_in, 1, "time");

    space = isl_space_set_tuple_name(space, isl_dim_in, "in");
    space = isl_space_set_tuple_name(space, isl_dim_out, "out");
    space = isl_space_set_dim_name(space, isl_dim_out, 0, "x'");
    space = isl_space_set_dim_name(space, isl_dim_out, 1, "time'");

```
### 2. Create a map from the space by using `isl_basic_map_universe`: 
```
{ in[x, time] -> out[stage, x', time'] :  }
```


Notice the difference between the map and the underlying space. The map has a `:` indicating that it can have dependencies applied on it.


C code:
```
    isl_basic_map *map = isl_basic_map_universe(space);

```

### 3. Create dependencies from input to output variables. 
```
{ in[x, time] -> out[x', time' = 1 + time] }
```

To do this, instantiate a `constraint` object, and setup the correct constraints between the input tuple value and the output tuple values. `isl` does the pretty printing for you.

Example C code:

```
    isl_local_space *ls = isl_local_space_from_space(space);
    isl_constraint *c = isl_constraint_alloc_equality(isl_local_space_copy(ls));
    c = isl_constraint_set_coefficient_si(c, isl_dim_out, 1, 1);
    c = isl_constraint_set_coefficient_si(c, isl_dim_in, 1, -1);
    c = isl_constraint_set_constant_si(c, -1);
    map = isl_basic_map_add_constraint(map, c);
```

Sorry for the trouble, and I hope this helps someone in the future.

**Comment by inducer** [comment]
Happy to hear you figured it out, and thanks for writing a note!
