### ISSUE TITLE
Tiling using islpy

### ISSUE THREAD

**Issue by abhishek111226** [inducer/islpy#7]
Hi, I want to perform scheduling followed by tiling using islpy. Till now, I was able to compute a schedule by setting appropriate validity constraints and able to extract a band by using get_band_forest() function. After this I want to tile each band.  For tiling a band, I need to use tile() function. But it needs vector of tile sizes.
My question is: How to know the number of tile sizes to be inserted into a vector so that a band can be tiled ?
In particular how to know dimensions of a band to provide that many tile sizes.
Currently my band looks like: 
({ S1[i, j] -> [] },{ S1[i, j] -> [i, i + j] },{ S1[i, j] -> [] })
Thank you in advance.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
