### ISSUE TITLE
Creating BasicSet from string prints to stderror

### ISSUE THREAD

**Issue by isuruf** [inducer/islpy#88]
Following throws a python error, but also prints to stderr.
```python
import islpy as isl
isl.BasicSet("{['/* im_x_inner */ lid(0)']}")
```

**Comment by inducer** [comment]
Can't be helped, short of redirecting stderr:

https://github.com/inducer/isl/blob/6a1760fe46967cda2a06387793a6b7d4a0876581/isl_stream.c#L132-L168

**Comment by isuruf** [comment]
Thanks. I'll check the validity of the string before passing.
